# ACTIONS_ID_TOKEN_REQUEST_URL: The URL for GitHub's OIDC provider.
# ACTIONS_ID_TOKEN_REQUEST_TOKEN: Bearer token for the request to the OIDC provider.

name: release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Post the token
        run: |
          export ID_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo $ID_TOKEN
          mvn -B clean test -e
