on:
  workflow_dispatch:

jobs:
  auth:
    permissions:
      contents: read
      id-token: write
  job:
    # ACTIONS_ID_TOKEN_REQUEST_URL: The URL for GitHub's OIDC provider.
    # ACTIONS_ID_TOKEN_REQUEST_TOKEN: Bearer token for the request to the OIDC provider.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Dump env
        run: env
